### ISSUE TITLE
extent of 4th (i.e., block) dimension of surface_forcing_diags should be nblocks_clinic

### ISSUE THREAD

**Issue by klindsay28** [marbl-ecosys/MARBL#102]
The variable surface_forcing_diags is currently allocated with extent in the block dimension as max_blocks_clinic. This dimension extent is used in subroutine ecosys_tavg_accumulate_flux to determine a local variable nblocks_cilnic. We should allocate with the extent actually being nblocks_clinic, so that these agree.

**Comment by mnlevy1981** [comment]
fixed in `marbl_dev_n22`
