### ISSUE TITLE
last argument in accumulate_tavg_field calls in ecosys_tavg_accumulate_flux is misleading

### ISSUE THREAD

**Issue by klindsay28** [marbl-ecosys/MARBL#103]
The variable i is being passed in as the last argument in these calls (which are for 2D fields).
This argument maps on to a k level argument in accumulate_tavg_field (and is ignored for 2D fields).
The convention in POP is to pass the value 1 in this situation.
Passing i, while harmless to model execution, is misleading.

While this is being fixed, please also make the case of the letters of the variable flux_diags consistent.
Right now, it appears as flux_diags, FLUX_DIAGS, and FLUX_diags.

**Comment by mnlevy1981** [comment]
fixed in `marbl_dev_n22`
