### ISSUE TITLE
units on *_RESTORE diagnostics are incorrect

### ISSUE THREAD

**Issue by klindsay28** [marbl-ecosys/MARBL#125]
Units should be marbl_tracer_metadata(n)%tend_units, not 'mmol/m^3'.

Additionally, there is a comment where marbl_interior_restore_diags is set up that reads
! Field we restore to
This is incorrect, as the diagnostic is the restoring tendency.

**Comment by mnlevy1981** [comment]
fixed in marbl0.13.0 release
