### ISSUE TITLE
reconsider declaration of shallow_depth in compute_vertical_integrals in marbl_diagnostics_mod.F90

### ISSUE THREAD

**Issue by klindsay28** [marbl-ecosys/MARBL#150]
current declaration is:
```
    real(kind=r8)      :: shallow_depth = 100.0e2_r8
```
this implies a save attribute, which we probably want to avoid in general, for thread safety.
One option is to add the parameter attribute, to indicate that this is never changed.

**Comment by mnlevy1981** [comment]
I added `shallow_depth` as an optional `intent(in)` argument to `compute_vertical_integrals()`, and if the argument is not present then `100.0e2_r8` is used. This seemed like a good extension of the interface, but if it's deemed overkill then we can use the `parameter` attribute instead.

**Comment by matt-long** [comment]
This seems like a good extension of the interface to me.

**Comment by mnlevy1981** [comment]
Fixed in [marbl0.26.0](https://github.com/NCAR/MARBL/releases/tag/marbl0.26.0)
