### ISSUE TITLE
POP needs to be able to get ndep from coupler

### ISSUE THREAD

**Issue by mnlevy1981** [marbl-ecosys/MARBL#152]
Make sure option is similar to iron flux (`driver-derived`?)

**Comment by klindsay28** [comment]
If iron flux is driver-derived, I would call this 'driver'.
It will be coming directly from the driver/flux-coupler with no additional computations,
so the derived suffix is not warranted, in my opinion.

**Comment by mnlevy1981** [comment]
This is available as of https://svn-ccsm-models.cgd.ucar.edu/pop2/branch_tags/marbl_dev_tags/marbl_dev_n42_cesm_pop_2_1_20170508/
