### ISSUE TITLE
tracer restoring tendency is only added to tracer tendencies for NO3, SiO3, PO4

### ISSUE THREAD

**Issue by klindsay28** [marbl-ecosys/MARBL#213]
Restoring tendencies can be generated for other tracers (and are for ALK in marginal seas in the CESM standard configuration), and the computed restoring tendencies are stored to diagnostics, but the tendencies are only added to the tracer tendencies in marbl_compute_dtracer_local for NO3, SiO3, and PO4.

**Comment by mnlevy1981** [comment]
Fixed in [marbl0.23.0](https://github.com/NCAR/MARBL/releases/tag/marbl0.23.0)
