### ISSUE TITLE
use CMIP/OMIP value for eps_k in marbl_ciso_mod.F90

### ISSUE THREAD

**Issue by klindsay28** [marbl-ecosys/MARBL#216]
The CMIP/OMIP value is -0.88, the average of the Zhang et al. (1995) values of -0.81 and -0.95 at 21C and 5C respectively. The code currently uses -0.81.

**Comment by mnlevy1981** [comment]
Fixed in [marbl0.24.3](https://github.com/NCAR/MARBL/releases/tag/marbl0.24.3)
