### ISSUE TITLE
add marbl_settings_consistency_check

### ISSUE THREAD

**Issue by klindsay28** [marbl-ecosys/MARBL#228]
call this from end of `subroutine init` in marbl_interface.F90

move existing consistency checks to this new subroutine
e.g., `if (ladjust_bury_coeff .and. (.not.lallow_glo_ops)) then`

**Comment by mnlevy1981** [comment]
Fixed in [marbl0.26.0](https://github.com/NCAR/MARBL/releases/tag/marbl0.26.0)
