### ISSUE TITLE
pass tracer_local to marbl_ciso_set_interior_forcing

### ISSUE THREAD

**Issue by klindsay28** [marbl-ecosys/MARBL#243]
simplifications that can then be done are
don't need `DIC_loc`, `O2_loc`, `NO3_loc` `DOCtot_loc` in `marbl_interior_share`
(compute `DOCtot_loc` in `marbl_ciso_set_interior_forcing`)
remove `setup_local_column_tracers`

investigate potential simplifications in `marbl_export_zooplankton_shared_variables`, `marbl_export_autotroph_shared_variables`, `setup_local_autotrophs`, `marbl_autotroph_consistency_check`

**Comment by mnlevy1981** [comment]
fixed in marbl0.28.8
