### ISSUE TITLE
zoo13c and zoo14c are not per-zooplankton tracers

### ISSUE THREAD

**Issue by klindsay28** [marbl-ecosys/MARBL#244]
correction belongs in `Per-zooplankton (ciso only)` block of default_settings.yaml
rename this block to `zooplankton (ciso only)`

**Comment by mnlevy1981** [comment]
Rename to `zoo13Ctot` and `zoo14Ctot` as well (consistent to `DO{13,14}Ctot`).

**Comment by mnlevy1981** [comment]
closed in marbl0.28.6
