### ISSUE TITLE
ecosys_restart_filename not always set properly

### ISSUE THREAD

**Issue by klindsay28** [marbl-ecosys/MARBL#246]
`ecosys_restart_filename` will not be set properly in `ecosys_tracers_and_saved_state_init` if ciso tracers are read from a different restart file than the base ecosys tracers. This could affect initialization of running mean variables.

**Comment by mnlevy1981** [comment]
Fix after the science code freeze but prior to the CESM 2.0 release

**Comment by mnlevy1981** [comment]
Fixed in [cesm_pop_2_1_20180514](https://svn-ccsm-models.cgd.ucar.edu/pop2/trunk_tags/cesm_pop_2_1_20180514/)
