### ISSUE TITLE
match code to lapply_nhx_surface_emis name and description

### ISSUE THREAD

**Issue by klindsay28** [marbl-ecosys/MARBL#248]
Pull request #162 changed the name and description of the setting related to nhx surface emissions. The new settings name is `lcompute_nhx_surface_emis` and the description is
"control if NHx emissions are computed".

However, the flag doesn't control if the emissions are computed.
It still controls if NHx emissions are subtracted from `stf(:,nh4_ind)`.
The code should be changed to match the setting's name and description.
If the flag is .false., then the emissions should not be computed (or subtracted from `stf`).

**Comment by mnlevy1981** [comment]
closed in marbl0.28.6
