### ISSUE TITLE
What should MARBL do if a requested surface forcing output is not computed?

### ISSUE THREAD

**Issue by klindsay28** [marbl-ecosys/MARBL#249]
MARBL has a settings flag `lflux_gas_co2` and a surface forcing output `flux_co2`.

MARBL is okay with the `flux_co2` being requested when `lflux_gas_co2=.false.`,
and it looks like MARBL returns 0 in that situation.

Is this the desired behavior? Should this be allowed?

On one hand, I think it doesn't make sense to request an output that is not being computed.

On the other hand, `lflux_gas_co2` is intended as a debugging tool (i.e., the ability to turn off some code is useful when debugging), and forcing the developer to turn off the request for `flux_co2` when setting `lflux_gas_co2=.false.` is a burden.

I'm on the fence. What do you other developers think?

**Comment by matt-long** [comment]
I agree with your second point, that the debugging utility of `lflux_gas_co2` should not require two switches to be flipped.  

Redundancy leads to ambiguity, however, so it would seem like a cleaner implementation, at least conceptually, would be for a switch to apply to the `flux_co2` request itself.

**Comment by mnlevy1981** [comment]
existing model behavior seems to be appropriate
