### ISSUE TITLE
updated default_settings values from jkmoore

### ISSUE THREAD

**Issue by klindsay28** [marbl-ecosys/MARBL#253]
The following are from an x1 tuning exercise.

For variables below that currently have different x3 and x1 values in default_settings.yaml, we should apply these values only to the x1 values. If the variable does not have different x3 and x1 values, apply these values unconditionally. That is, do not introduce new grid dependencies.

 grazing(2,1)%z_umax_0_per_day = 3.1
 grazing(3,1)%z_umax_0_per_day = 3.25

 autotrophs(3)%PCref_per_day = 2.5

 parm_FeLig_scavenge_rate0 = 1.4
 parm_Fe_scavenge_rate0 = 18

 autotrophs(1)%gQfe_min = 2.7e-06
 autotrophs(2)%gQfe_min = 2.7e-06
 autotrophs(3)%gQfe_min = 5.4e-06

 parm_scalelen_vals(1) = 1
 parm_scalelen_vals(2) = 3.0
 parm_scalelen_vals(3) = 4.5
 parm_scalelen_vals(4) = 5.5

**Comment by mnlevy1981** [comment]
closed in marbl0.28.5
