### ISSUE TITLE
introduce caco3_bury_thres_omega_calc for caco3_bury_thres_opt='omega_calc'

### ISSUE THREAD

**Issue by klindsay28** [marbl-ecosys/MARBL#264]
An anticipated knob for tuning alk balance is to change the omega_calc threshold for burying CaCO3, when caco3_bury_thres_opt='omega_calc'. This issue is to introduce a settings var to be this knob. The initial implementation will (hopefully) not be answer changing.

**Comment by mnlevy1981** [comment]
fixed in marbl0.28.9
