### ISSUE TITLE
Need way to reproduce older science in latest code base

### ISSUE THREAD

**Issue by mnlevy1981** [marbl-ecosys/MARBL#274]
As we tune CESM for CMIP6, it looks like the CESM 2.1 release will have different default parameter values than the CESM 2.0 release. We want to support running CESM 2.1 with the CESM 2.0 BGC set-up, though, so we need a way to specify "use all of the CESM 2.0 default parameter values." Some specific points came up in discussion with @matt-long and @klindsay28 

* We want to keep multiple copies of `default_settings.{yaml,json}` in the MARBL repository; e.g. `default_settings.yaml` and `default_settings-cesm2_0.yaml`. We do NOT want the GCM to own the old default files because
   1. We want all the default settings files co-located so a user that goes looking for the file generating default values does not stumble upon the wrong file
   1. The old defaults may need to be updated when a new parameter is added to the model; we do not want that situation to require GCM source mods
* Maybe instead of keeping YAML files in `src/` and JSON files in `autogenerated_src/`, we should have the YAML in a new `defaults/` directory and JSON in `defaults/json/` or `defaults/autogenerated_json/`
* POP will have tests running with the old science that should be bit-for-bit when only the latest science is updated

**Comment by mnlevy1981** [comment]
Talking with @klindsay28 we decided the best approach is to have the following YAML files (path relative to root of MARBL clone):

```
defaults/diagnostics_latest.yaml
defaults/settings_cesm2.0.yaml
defaults/settings_latest.yaml

defaults/json/diagnostics_latest.json
defaults/json/settings_cesm2.0.json
defaults/json/settings_latest.json
```

This takes the YAML files out of `src/` and the JSON files out of `autogenerated_src/` (the `autogenerated_src/` directory is now empty, so git removes it from the repository -- we may want to put it back in once we start generating Fortran code from the JSON).

I have a branch of MARBL with this new file structure, and POP has been updated (on `marbl_dev_levy`) to use `diagnostics_latest.json` and `settings_latest.json`.

****

The next step will be to introduce a new `env_run.xml` variable to let us specify a different JSON file to use. I am envisioning something like `MARBL_SETTINGS_DEFAULTS`, with valid values of `latest` (the default) and `cesm2.0` -- a CESM 2.1 user that wants to use the MARBL parameter values from CESM 2.0 would then run

```
$ ./xmlchange MARBL_SETTINGS_DEFAULTS=cesm2.0
```

and the `MARBL_scripts/MARBL_wrappers/MARBL_settings.py` will look for `settings_cesm2.0.json` instead of `settings_latest.json`.

For now we will not provide a way to change the default diagnostics, but if that is desired I think it will be pretty straightforward to add something like

```
$ ./xmlchange MARBL_DIAGS_DEFAULTS=cmip6
```
and update `MARBL_scripts/MARBL_wrappers/MARBL_diagnostics.py` in a similar manner.

**Comment by mnlevy1981** [comment]
Also, documentation will need to be updated. The following pages all reference YAML:

1. https://marbl-ecosys.github.io/versions/latest/dev-guide/add-diagnostic.html
1. https://marbl-ecosys.github.io/versions/latest/dev-guide/add-settings-parameter.html
1. https://marbl-ecosys.github.io/versions/latest/dev-guide/add-tracer.html

Note that the first two pages don't actually mention where the YAML is located, and that should be fixed.

**Comment by klindsay28** [comment]
There are also some ecosys namelist vars in POP that are changing between CESM 2.0 and 2.1 (e.g. ndep forcing files, fesedflux, ...). It might be convenient if the env_run variable controlling the MARBL settings defaults can control these POP namelist defaults too. So maybe the env_run variable could be something like OCN_BGC_CONFIG, and not include MARBL in its name.

**Comment by mnlevy1981** [comment]
This is available as of marbl0.31.0.
