### ISSUE TITLE
Remove all unused variables

### ISSUE THREAD

**Issue by mnlevy1981** [marbl-ecosys/MARBL#276]
From #87 -- "NAG provides warnings about variables that are declared but not used, which will be very useful once the code is stable. Also, if we can reach a point where the code compiles without warnings it would be nice to turn on a compile flag to elevate warnings to errors in the test system to ensure the code stays that way."

**Comment by klindsay28** [comment]
Adding -Wall to CFLAGS for gnu will catch this, and can be caught by travis-ci.
Once we eliminate all warnings from gnu -Wall, we can add -Werror and travis-ci will keep us honest.
