### ISSUE TITLE
have travis-ci verify that json files are up to date

### ISSUE THREAD

**Issue by klindsay28** [marbl-ecosys/MARBL#300]
I think it would be useful if travis-ci could run yaml_to_json.py and verify that the resulting json files are the same as the committed json files.

**Comment by mnlevy1981** [comment]
This is a great idea and easy to implement - I'll bring it in with #298 since I'm already changing `run_test_suite.sh` in that PR.

**Comment by mnlevy1981** [comment]
fixed in [marbl0.31.1](https://github.com/marbl-ecosys/MARBL/releases/tag/marbl0.31.1)
