### ISSUE TITLE
change interface so that interior_tendency_compute returns vertical tracer flux at sea floor

### ISSUE THREAD

**Issue by klindsay28** [marbl-ecosys/MARBL#360]
`interior_tendency_compute` currently computes vertical tracer flux at the sea floor and adds the effect of this to `interior_tendencies`, in the 'bottom' model layer. This will be problematic in MOM6 when there are multiple vanishingly thin layers at the sea floor, as MARBL will generate very large tendencies in the bottom layer.

If MARBL returns this vertical tracer flux, then the GCM can apply it as is appropriate for the GCM. For GCM=MOM6, the flux can be an argument to MOM6's `tracer_vertdiff` subroutine. This will handle the presence of thin layers at the sea floor. For GCM=POP, the flux can be converted into a tendency in the model's bottom layer, as MARBL currently does. This will probably introduce roundoff differences in POP/MARBL solutions.

Note that the computation of some elemental conservation diagnostics (`Jint_{C,N,P,Si,Fe}tot`) will need to be updated to include these sea floor fluxes.

**Comment by mnlevy1981** [comment]
closed by #381 (which was a better fix than #377)
