### ISSUE TITLE
Remove mask from interface?

### ISSUE THREAD

**Issue by mnlevy1981** [marbl-ecosys/MARBL#84]
Right now, the GCM needs to provide a land mask to MARBL before MARBL can set surface forcings... but no mask is needed for interior forcing. This difference came about because MARBL can update the surface forcing on a 1D array of grid points, while interior forcing is done gridcell by gridcell so the GCM only calls MARBL from ocean grid points. Removing the land mask from the `marbl_forcing_fields_type` datatype (and having the GCM only "pack" data from the ocean cells into the MARBL datatypes) would allow us to clean up the surface forcing code and also provide some consistency between the surface and interior forcing interfaces.

**Comment by mnlevy1981** [comment]
Note that this will not require an API change in MARBL so I think we should punt on it until after the 1.0.0 release

**Comment by klindsay28** [comment]
When POP starts passing only ocean points to MARBL for surface flux computations, it should only pass ocean points within the phys domain, not halo points. This will also make halo updates of forcing_fields unnecessary.

**Comment by mnlevy1981** [comment]
Fixed as of marbl0.15.0
