### ISSUE TITLE
POP driver only restores to time-invariant fields

### ISSUE THREAD

**Issue by mnlevy1981** [marbl-ecosys/MARBL#97]
With Tony's 4D stream update, we can read in time-varying 3D data and pass appropriate time slice to MARBL.

Also: we need an option to restore only marginal seas (or specify a regional mask for where to apply restoring)

**Comment by mnlevy1981** [comment]
Notes from MARBL meeting:
1. Use `shr_stream` for all restoring in ecosys (even if we are restoring to time-invariant field) => no need for `restore_type` namelist variable.
2. Restoring should depend on a mask variable it reads in rather than POP's internal region masks (this will NOT be variable-specific, so all variables will be restored in the same regions).

**Comment by klindsay28** [comment]
implemented with marbl_dev_n37
